.class public final Lkotlinx/parcelize/Parceler$DefaultImpls;
.super Ljava/lang/Object;
.source "Parceler.kt"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lkotlinx/parcelize/Parceler;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "DefaultImpls"
.end annotation

.annotation runtime Lkotlin/Metadata;
    k = 0x3
    mv = {
        0x1,
        0x9,
        0x0
    }
    xi = 0x30
.end annotation


# direct methods
.method public static newArray(Lkotlinx/parcelize/Parceler;I)[Ljava/lang/Object;
    .locals 2
    .param p0, "$this"    # Lkotlinx/parcelize/Parceler;
    .param p1, "size"    # I
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlinx/parcelize/Parceler<",
            "TT;>;I)[TT;"
        }
    .end annotation

    .line 40
    new-instance v0, Lkotlin/NotImplementedError;

    const-string v1, "Generated by Android Extensions automatically"

    invoke-direct {v0, v1}, Lkotlin/NotImplementedError;-><init>(Ljava/lang/String;)V

    throw v0
.end method
